# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d57f3e1fbf77609b2b518aa00832e2fcf07dd60e42449943e0cac9dbcc70dc533152769043803ab946882f251dcc14ac2a8fdb2c6c2dd0e3fbf458efeef59f4

test:
  secret_key_base: 763a969237600c38edc91ed4dac55a51f95b7fd4dca37a63edff2a5317219ea440bf10abadc4fa9986281eeb0fff5d377312e9b0df88c96fab1d758bec4ca53d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
